import numpy as np

# Physics and Simulation Parameters
ALPHA = 1.0
DT = 0.2
LF_NSUB = 1
HF_NSUB = 40
HF_NOISE = 0.02
WAVENUM_RANGE = (-5, 5)  # Set to (-5, 5) for meaningful fidelity gap

# Mesh Parameters
N_LF = 64
N_HF = 256
K_NN = 6

# Data Parameters
N_LF_SNAPS = 150
N_HF_POOL = 150
N_TEST = 40
N_HF_SCARCE = 10
N_SEEDS = 4
N_SEEDS_EFF = 3
SNAP_COUNTS = [5, 10, 20, 50, 100, 140]

# Training Hyperparameters
PRETRAIN_EPOCHS = 900
PRETRAIN_LR = 0.009943323735557428 # was 0.005
LAMBDA_PDE_PRE = 0.9037191902260121 # was 0.5

FINETUNE_EPOCHS = 800
FINETUNE_LR = 0.00035397284510561627 # was 0.003
LAMBDA_PDE_FT = 0.1

BASELINE_EPOCHS = 1200
BASELINE_LR = 0.005

HIDDEN_DIM = 32

config = {
    "ALPHA": ALPHA, "DT": DT, "LF_NSUB": LF_NSUB, "HF_NSUB": HF_NSUB,
    "HF_NOISE": HF_NOISE, "WAVENUM_RANGE": list(WAVENUM_RANGE),
    "N_LF": N_LF, "N_HF": N_HF, "K_NN": K_NN,
    "N_LF_SNAPS": N_LF_SNAPS, "N_HF_POOL": N_HF_POOL, "N_TEST": N_TEST,
    "N_HF_SCARCE": N_HF_SCARCE, "N_SEEDS": N_SEEDS, "N_SEEDS_EFF": N_SEEDS_EFF,
    "SNAP_COUNTS": SNAP_COUNTS,
    "PRETRAIN_EPOCHS": PRETRAIN_EPOCHS, "PRETRAIN_LR": PRETRAIN_LR, "LAMBDA_PDE_PRE": LAMBDA_PDE_PRE,
    "FINETUNE_EPOCHS": FINETUNE_EPOCHS, "FINETUNE_LR": FINETUNE_LR, "LAMBDA_PDE_FT": LAMBDA_PDE_FT,
    "BASELINE_EPOCHS": BASELINE_EPOCHS, "BASELINE_LR": BASELINE_LR,
    "HIDDEN_DIM": HIDDEN_DIM
}